// src/components/Navbar.jsx
import { useState, useEffect, useRef } from 'react';
import logoGif from '../assets/logo.gif';
import '../logo_styles.css';
import { motion, AnimatePresence } from 'framer-motion';
import { ThemeTogglerButton } from '@/components/animate-ui/components/buttons/theme-toggler';

const RevealText = ({ text }) => (
  <div style={{ position:'relative', overflow:'hidden', height:'1.2em', lineHeight:'1.2em' }}>
    <motion.div
      variants={{ hover:{ y:'-50%' }, initial:{ y:'0%' } }}
      transition={{ duration:0.3, ease:[0.33,1,0.68,1] }}
      style={{ display:'flex', flexDirection:'column' }}
    >
      <span>{text}</span>
      <span style={{ background:'var(--gradient)', WebkitBackgroundClip:'text', WebkitTextFillColor:'transparent', backgroundClip:'text' }}>{text}</span>
    </motion.div>
  </div>
);

const Navbar = ({ onRefresh, onLogoClick, isTourActive, isLoaded }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [theme, setTheme] = useState(() => {
    return localStorage.getItem('portfolio-theme') || 'dark';
  });
  const [activeSection, setActiveSection] = useState('');
  const [scrolled, setScrolled] = useState(false);
  const visibilityMap = useRef({});

  useEffect(() => {
    document.body.setAttribute('data-theme', theme);
    localStorage.setItem('portfolio-theme', theme);
  }, [theme]);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  useEffect(() => {
    if (!isLoaded) return;
    const sections = document.querySelectorAll('section[id], header[id]');
    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        visibilityMap.current[entry.target.id] = entry.isIntersecting ? entry.intersectionRatio : 0;
      });
      const [topId] = Object.entries(visibilityMap.current)
        .reduce((best, [id, ratio]) => ratio > best[1] ? [id, ratio] : best, ['', 0]);
      if (topId) setActiveSection(topId);
    }, { threshold: [0, 0.1, 0.25, 0.5, 0.75, 1] });
    sections.forEach(s => observer.observe(s));
    return () => observer.disconnect();
  }, [isLoaded]);

  const navLinks = [
    { id:'home',    label:'Home' },
    { id:'about',   label:'About' },
    { id:'resume',  label:'Resume' },
    { id:'project', label:'Projects' },
    { id:'service', label:'Skills' },
    { id:'blog',    label:'Blog' },
    { id:'contact', label:'Contact', isBtn: true },
  ];

  return (
    <nav className="navbar-futuristic">
      <div className="nav__bar" style={scrolled ? { boxShadow:'0 8px 40px rgba(0,0,0,0.4)', borderColor:'rgba(232,184,75,0.2)' } : {}}>
        <div className="nav__header">
          <div className="nav__logo">
            <a href="#home" className="nav-logo-link" onClick={(e) => {
              if (onLogoClick) { e.preventDefault(); onLogoClick(); }
            }}>
              <img
                src={logoGif}
                alt="Satish Pakalapati"
                title="Satish Pakalapati"
                className={`nav-logo-gif ${isTourActive ? 'nav-logo-rotating' : ''}`}
              />
              {isTourActive && <span className="nav-tour-text">Click to Stop</span>}
            </a>
          </div>
          <div className="nav__menu__btn" id="menu-btn" onClick={() => setIsOpen(!isOpen)}>
            <span><i className={isOpen ? 'ri-close-line' : 'ri-menu-3-line'}></i></span>
          </div>
        </div>

        <ul className={`nav__links ${isOpen ? 'open' : ''}`} id="nav-links">
          {navLinks.map(link => (
            <li key={link.id} className={`link ${link.isBtn ? 'btn' : ''} ${activeSection === link.id ? 'active' : ''}`}>
              <motion.a
                href={`#${link.id}`}
                onClick={(e) => {
                  e.preventDefault();
                  setIsOpen(false);
                  if (link.id === 'home' && onRefresh) onRefresh();
                  const el = document.getElementById(link.id);
                  if (el) el.scrollIntoView({ behavior: 'smooth' });
                  setActiveSection(link.id);
                }}
                className="relative link-item block"
                initial="initial"
                whileHover="hover"
                style={{ overflow: 'visible', paddingBottom: '6px' }}
              >
                <span className="relative z-10 block">
                  <RevealText text={link.label} />
                </span>
                {activeSection === link.id && !link.isBtn && (
                  <span className="active-line" />
                )}
              </motion.a>
            </li>
          ))}
          <li className="theme-toggle">
            <ThemeTogglerButton currentTheme={theme} onThemeChange={setTheme} />
          </li>
        </ul>
      </div>
    </nav>
  );
};

export default Navbar;

// src/app/components/navbar/navbar.component.ts
import { CommonModule } from '@angular/common';
import { AfterViewInit, Component, OnDestroy, OnInit } from '@angular/core';
import { scrollToSection } from '../../shared/section-navigation';

type Theme = 'dark' | 'light';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <nav class="navbar-futuristic">
      <div class="nav__bar">
        <div class="nav__header">
          <a href="/home" class="nav-logo-link" aria-label="Satish Pakalapati home" (click)="goTo($event, 'home')">
            <img class="nav-logo-gif" src="assets/logo.gif" alt="Satish Pakalapati logo" />
          </a>
          <button class="nav__menu__btn" type="button" aria-label="Toggle navigation" (click)="isMenuOpen = !isMenuOpen">
            <i [class]="isMenuOpen ? 'ri-close-line' : 'ri-menu-3-line'"></i>
          </button>
        </div>

        <ul class="nav__links" [class.open]="isMenuOpen">
          <li *ngFor="let link of navLinks" class="link" [class.btn]="link.isButton" [class.active]="activeSection === link.id">
            <a [href]="'/' + link.id" (click)="goTo($event, link.id)">
              <span>{{ link.label }}</span>
              <span *ngIf="activeSection === link.id && !link.isButton" class="active-line"></span>
            </a>
          </li>
          <li>
            <button class="theme-switch" type="button" (click)="toggleTheme()" [attr.aria-label]="'Switch to ' + (theme === 'dark' ? 'light' : 'dark') + ' theme'">
              <i [class]="theme === 'dark' ? 'ri-sun-line' : 'ri-moon-line'"></i>
            </button>
          </li>
        </ul>
      </div>
    </nav>
  `,
})
export class NavbarComponent implements OnInit, AfterViewInit, OnDestroy {
  readonly navLinks = [
    { id: 'home', label: 'Home' },
    { id: 'about', label: 'About' },
    { id: 'resume', label: 'Resume' },
    { id: 'project', label: 'Projects' },
    { id: 'service', label: 'Skills' },
    { id: 'blog', label: 'Blog' },
    { id: 'contact', label: 'Contact', isButton: true },
  ];

  theme: Theme = 'dark';
  isMenuOpen = false;
  activeSection = 'home';

  private observer?: IntersectionObserver;

  ngOnInit(): void {
    const savedTheme = localStorage.getItem('portfolio-theme') as Theme | null;
    this.theme = savedTheme === 'light' ? 'light' : 'dark';
    document.body.setAttribute('data-theme', this.theme);
    this.activeSection = window.location.hash.replace('#', '') || 'home';
  }

  ngAfterViewInit(): void {
    this.observeSections();
  }

  ngOnDestroy(): void {
    this.observer?.disconnect();
  }

  toggleTheme(): void {
    this.theme = this.theme === 'dark' ? 'light' : 'dark';
    localStorage.setItem('portfolio-theme', this.theme);
    document.body.setAttribute('data-theme', this.theme);
  }

  goTo(event: Event, id: string): void {
    event.preventDefault();
    this.isMenuOpen = false;
    this.activeSection = id;
    scrollToSection(id);
  }

  private observeSections(): void {
    const visibility = new Map<string, number>();
    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => visibility.set(entry.target.id, entry.isIntersecting ? entry.intersectionRatio : 0));
        let bestId = this.activeSection;
        let bestRatio = 0;
        visibility.forEach((ratio, id) => {
          if (ratio > bestRatio) {
            bestId = id;
            bestRatio = ratio;
          }
        });
        this.activeSection = bestId;
      },
      { threshold: [0, 0.2, 0.5, 0.8] },
    );

    document.querySelectorAll('section[id], header[id]').forEach((section) => this.observer?.observe(section));
  }
}

<nav class="navbar-futuristic">
  <div class="nav__bar">
    <div class="nav__header">
      <a href="/home" class="nav-logo-link" aria-label="Satish Pakalapati home" (click)="goTo($event, 'home')">
        <img class="nav-logo-gif" src="assets/logo.gif" alt="Satish Pakalapati logo" />
      </a>
      <button class="nav__menu__btn" type="button" aria-label="Toggle navigation" (click)="isMenuOpen = !isMenuOpen">
        <i [class]="isMenuOpen ? 'ri-close-line' : 'ri-menu-3-line'"></i>
      </button>
    </div>

    <ul class="nav__links" [class.open]="isMenuOpen">
      <li *ngFor="let link of navLinks" class="link" [class.active]="activeSection === link.id">
        <a [href]="'/' + link.id" (click)="goTo($event, link.id)">
          <span>{{ link.label }}</span>
          <span *ngIf="activeSection === link.id" class="active-line"></span>
        </a>
      </li>
      <li>
        <button class="theme-switch" type="button" (click)="toggleTheme()" [attr.aria-label]="'Switch to ' + (theme === 'dark' ? 'light' : 'dark') + ' theme'">
          <i [class]="theme === 'dark' ? 'ri-sun-line' : 'ri-moon-line'"></i>
        </button>
      </li>
    </ul>
  </div>
</nav>
